version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=foodstallorders
      - MYSQL_DATABASE=foodstallorders
    expose:
      - 3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:  
      - "8000:8000"
    # command to sleep for 30 seconds and then run npm start
    command: sh -c "sleep 30; npm start"
  frontend:
    build: ./client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000" 